language: python
sudo: required
python:
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'

env:
  - TEST_SUITE=tests
  - TEST_SUITE=tests_integ

install:
  - unset PYTHONWARNINGS
  # Install all Python requirements (application and tests)
  - ./tests/setup_test.sh
  # To help eventual debug: knowing which exact versions are in use can be rather useful.
  - pip freeze

script:
  - echo "Starting tests '$TEST_SUITE' ..."
  - |
    # Run tests suite with code coverage analysis
    cd $TEST_SUITE
    echo "Starting tests '$TEST_SUITE' ..."
    pytest --verbose --durations=10 --no-print-logs --cov=fusionsupervision --cov-config .coveragerc test_*.py || travis_terminate 1;
    # Upload coverage results to codecov
    bash <(curl -s https://codecov.io/bash) -e $TEST_SUITE -c -F $TEST_SUITE
    cd ..
after_success:
jobs:
  include:
    - stage: Coding standard
      script:
        # Static code analysis
        # -- pycodestyle (former pep8)
        - pycodestyle --max-line-length=100 --exclude='*.pyc,carboniface.py' fusionsupervision/*
        # -- pylint
        - pylint --rcfile=.pylintrc -r no fusionsupervision
        # -- pep257
        - pep257 --select=D300 fusionsupervision
    - stage: Pypi deployment
      script: echo "Deploying to PyPi..."
      if: (tag IS present)
      deploy:
      - provider: pypi
        distributions: "sdist bdist_wheel"
        skip_existing: true
        on:
          tags: true
        user: fusionsupervision
        password:
          secure: "xxx"
    - stage: Debian packaging - python 2
      python: 2.7
      if: (tag IS blank)
      script:
        - echo "Packaging for BinTray..."
        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION deb
      deploy:
      - provider: bintray
        skip_cleanup: true
        file: dist/.bintray-deb.json
        on:
          all_branches: true
        user: fusionsupervision
        key:
          secure: "xxx"
    - stage: Debian packaging - python 3
      python: 3.6
      if: (tag IS blank)
      script:
        - echo "Packaging for BinTray..."
        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION deb
      deploy:
      - provider: bintray
        skip_cleanup: true
        file: dist/.bintray-deb.json
        on:
          all_branches: true
        user: fusionsupervision
        key:
          secure: "xxx"
    - stage: RPM packaging - python 2
      python: 2.7
      if: (tag IS blank)
      install:
        - echo "Installing packaging requirements..."
        - sudo apt-get install -y rpm
      script:
        - echo "Packaging for BinTray..."
        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION rpm
      deploy:
      - provider: bintray
        skip_cleanup: true
        file: dist/.bintray-rpm.json
        on:
          all_branches: true
        user: fusionsupervision
        key:
          secure: "xxx"
    - stage: RPM packaging - python 3
      python: 3.6
      if: (tag IS blank)
      install:
        - echo "Installing packaging requirements..."
        - sudo apt-get install -y rpm
      script:
        - echo "Packaging for BinTray..."
        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION rpm
      deploy:
      - provider: bintray
        skip_cleanup: true
        file: dist/.bintray-rpm.json
        on:
          all_branches: true
        user: fusionsupervision
        key:
          secure: "xxx"
#    - stage: FreeBSD packaging - python 2
#      python: 2.7
#      if: (tag IS blank)
#      script:
#        - echo "Packaging for BinTray..."
#        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION freebsd
#      deploy:
#      - provider: bintray
#        skip_cleanup: true
#        file: dist/.bintray-freebsd.json
#        on:
#          all_branches: true
#        user: fusionsupervision
#        key:
#          secure: "xxx"
#    - stage: FreeBSD packaging - python 3
#      python: 3.6
#      if: (tag IS blank)
#      script:
#        - echo "Packaging for BinTray..."
#        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION freebsd
#      deploy:
#      - provider: bintray
#        skip_cleanup: true
#        file: dist/.bintray-freebsd.json
#        on:
#          all_branches: true
#        user: fusionsupervision
#        key:
#          secure: "xxx"
